#this makes sure that when you make a pull_request your code must at least compile for the pull_request to be allowed.
name: Secrets workflow

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"


on:
  pull_request:
    branches: ["main"]

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "secrets"

    steps:
      - name: echo environment variable
        run: echo "The value of $JOB_NAME is $API_CSPROJ_PATH"

  new_job:
    name: Secrets Demo
    runs-on: ubuntu-latest
    env:
      JOB_NAME: "new_job"

    steps:
      - name: echo environment variable
        run: echo "The value of $JOB_NAME is $API_CSPROJ_PATH"  