#this makes sure that when you make a pull_request your code must at least compile for the pull_request to be allowed.
name: Secrets workflow

env:
  API_CSPROJ_PATH: "./src/GitHubActionsDotNet.Api/GitHubActionsDotNet.Api.csproj"


on:
  pull_request:
    branches: ["main"]

jobs:
  secrets:
    name: Secrets Demo
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"